//! The real Envoy dynamic-module ABI binding (feature `sdk`, ADR-004).
//!
//! This is the one host-gated seam: it depends on the OFFICIAL upstream Envoy
//! dynamic-modules SDK (`envoy-proxy-dynamic-modules-rust-sdk`, pinned to the
//! Envoy release tag — the ABI hash is checked at load, so SDK tag ⇔ image tag).
//! It adapts the SDK's synchronous filter callbacks to the pure [`Module`] driver
//! — buffer the request, run the brain on the runtime, and apply the effects to
//! the Envoy handle.
//!
//! **Generic over your tenancy.** The glue here is generic over any
//! [`Router`](osproxy_tenancy::Router); a module is built from a *factory*
//! (`fn(&str) -> R`) that turns Envoy's `filter_config` blob into your router. You
//! do not edit this file — you invoke [`register!`](crate::register) in your own
//! cdylib with your factory, and the SDK is pulled in transitively. See the crate
//! README and `examples/custom-module`.

use std::sync::Arc;

use envoy_proxy_dynamic_modules_rust_sdk::{
    abi, EnvoyHttpFilter, EnvoyHttpFilterConfigImpl, EnvoyHttpFilterImpl, HttpFilter,
    HttpFilterConfig, NewHttpFilterConfigFunction, NEW_HTTP_FILTER_CONFIG_FUNCTION,
};
use evoxy_abi::{FilterRequest, HttpVersion, MtlsIdentity};
use evoxy_filter::{EnvoyActions, FilterDecision};
use osproxy_tenancy::Router;
use tokio::runtime::Runtime;

use crate::Module;

// Re-export the concrete SDK types the `register!` macro names, so a user's cdylib
// never has to depend on (or even name) the upstream SDK crate directly.
pub use envoy_proxy_dynamic_modules_rust_sdk::{
    EnvoyHttpFilterConfigImpl as ConfigHandle, EnvoyHttpFilterImpl as FilterHandle,
    HttpFilterConfig as SdkHttpFilterConfig,
};

/// Install the config factory as Envoy's `on_program_init` handler and return the
/// SDK's ABI-version string (what Envoy verifies at load). Called once, by the
/// [`register!`](crate::register) macro's generated init function.
#[must_use]
pub fn install(
    new_config: NewHttpFilterConfigFunction<EnvoyHttpFilterConfigImpl, EnvoyHttpFilterImpl>,
) -> *const std::os::raw::c_char {
    let _ = NEW_HTTP_FILTER_CONFIG_FUNCTION.set(new_config);
    abi::kAbiVersion.as_ptr().cast::<std::os::raw::c_char>()
}

/// Build a per-filter-chain config from Envoy's `filter_config` blob and a router
/// factory. The [`register!`](crate::register) macro calls this with your factory;
/// it spins up the one-thread runtime the module drives its async work on and wraps
/// your [`Router`] in the [`Module`] brain.
pub fn new_config<R, EHF>(
    filter_config: &[u8],
    factory: fn(&str) -> R,
) -> Option<Box<dyn HttpFilterConfig<EHF>>>
where
    R: Router + Send + Sync + 'static,
    EHF: EnvoyHttpFilter,
{
    let config = String::from_utf8_lossy(filter_config).into_owned();
    // Single worker: the reference/in-memory placements resolve without network I/O,
    // so `block_on` never parks on a socket (ADR-004). A factory that needs more can
    // be given a fatter runtime by the user's own `new_config` variant.
    let runtime = tokio::runtime::Builder::new_multi_thread()
        .worker_threads(1)
        .enable_all()
        .build()
        .ok()?;
    let module = Module::new(factory(&config), runtime.handle().clone());
    Some(Box::new(EvoxyConfig {
        shared: Arc::new(Shared {
            _runtime: runtime,
            module,
        }),
    }))
}

/// Per-filter-chain state, shared across request instances. Holds the runtime that
/// drives the async pipeline from Envoy's synchronous callbacks, and the brain.
struct Shared<R> {
    // Kept alive for the config's lifetime; the module holds its `Handle`.
    _runtime: Runtime,
    module: Module<R>,
}

/// The SDK filter-config object (one per filter-chain configuration).
struct EvoxyConfig<R> {
    shared: Arc<Shared<R>>,
}

impl<R, EHF> HttpFilterConfig<EHF> for EvoxyConfig<R>
where
    R: Router + Send + Sync + 'static,
    EHF: EnvoyHttpFilter,
{
    fn new_http_filter(&self, _envoy: &mut EHF) -> Box<dyn HttpFilter<EHF>> {
        Box::new(EvoxyFilter {
            shared: self.shared.clone(),
            headers: Vec::new(),
        })
    }
}

/// Per-request instance: captures the headers at the header phase, then runs the
/// brain — at the header phase for a body-less request (a read), otherwise once the
/// body is fully buffered.
struct EvoxyFilter<R> {
    shared: Arc<Shared<R>>,
    headers: Vec<(String, String)>,
}

impl<R, EHF> HttpFilter<EHF> for EvoxyFilter<R>
where
    R: Router + Send + Sync + 'static,
    EHF: EnvoyHttpFilter,
{
    fn on_request_headers(
        &mut self,
        envoy: &mut EHF,
        end_of_stream: bool,
    ) -> abi::envoy_dynamic_module_type_on_http_filter_request_headers_status {
        self.headers = envoy
            .get_request_headers()
            .into_iter()
            .map(|(k, v)| {
                (
                    String::from_utf8_lossy(k.as_slice()).into_owned(),
                    String::from_utf8_lossy(v.as_slice()).into_owned(),
                )
            })
            .collect();
        if end_of_stream {
            // No body (a read): run the brain now.
            self.process(envoy, Vec::new());
            abi::envoy_dynamic_module_type_on_http_filter_request_headers_status::Continue
        } else {
            // A write: the body-dependent transform waits for the buffered body, but
            // the upstream cluster is already known from the headers. Set it now, at
            // the header phase, so Envoy routes on `x-evoxy-cluster` before the body
            // arrives — a body-phase override lands after the route is chosen and is
            // ignored (why per-tenant routing needs this). A resolution error here
            // fails closed immediately.
            let req = build_request(&self.headers, Vec::new());
            let mut actions = SdkActions::new(Vec::new());
            let decision = self.shared.module.route_headers(&req, &mut actions);
            actions.apply(envoy);
            if decision == FilterDecision::StoppedWithLocalReply {
                // Already replied (fail-closed); do not wait for a body.
                return abi::envoy_dynamic_module_type_on_http_filter_request_headers_status::Continue;
            }
            abi::envoy_dynamic_module_type_on_http_filter_request_headers_status::StopIteration
        }
    }

    fn on_request_body(
        &mut self,
        envoy: &mut EHF,
        end_of_stream: bool,
    ) -> abi::envoy_dynamic_module_type_on_http_filter_request_body_status {
        if !end_of_stream {
            return abi::envoy_dynamic_module_type_on_http_filter_request_body_status::StopIterationAndBuffer;
        }
        let body = envoy
            .get_buffered_request_body()
            .map(|slices| slices.iter().flat_map(|s| s.as_slice().to_vec()).collect())
            .unwrap_or_default();
        self.process(envoy, body);
        abi::envoy_dynamic_module_type_on_http_filter_request_body_status::Continue
    }

    fn on_response_headers(
        &mut self,
        _envoy: &mut EHF,
        end_of_stream: bool,
    ) -> abi::envoy_dynamic_module_type_on_http_filter_response_headers_status {
        if end_of_stream {
            // No body to reshape (e.g. a bodyless response); let it through.
            abi::envoy_dynamic_module_type_on_http_filter_response_headers_status::Continue
        } else {
            // Hold the response headers until the body is reshaped, so the updated
            // `content-length` goes out with the (possibly grown/shrunk) body.
            abi::envoy_dynamic_module_type_on_http_filter_response_headers_status::StopIteration
        }
    }

    fn on_response_body(
        &mut self,
        envoy: &mut EHF,
        end_of_stream: bool,
    ) -> abi::envoy_dynamic_module_type_on_http_filter_response_body_status {
        if !end_of_stream {
            return abi::envoy_dynamic_module_type_on_http_filter_response_body_status::StopIterationAndBuffer;
        }
        let body: Vec<u8> = envoy
            .get_buffered_response_body()
            .map(|slices| slices.iter().flat_map(|s| s.as_slice().to_vec()).collect())
            .unwrap_or_default();
        // Reshape into the client's logical view (strip injected fields, unmap ids),
        // recomputing the placement from the captured request headers.
        let req = build_request(&self.headers, Vec::new());
        if let Some(shaped) = self.shared.module.on_response(&req, &body) {
            let existing = envoy.get_buffered_response_body_size();
            if existing > 0 {
                envoy.drain_buffered_response_body(existing);
            }
            envoy.append_buffered_response_body(&shaped);
            envoy.set_response_header("content-length", shaped.len().to_string().as_bytes());
        }
        abi::envoy_dynamic_module_type_on_http_filter_response_body_status::Continue
    }
}

impl<R> EvoxyFilter<R>
where
    R: Router + Send + Sync + 'static,
{
    /// Build the request, run the brain, and apply the recorded effects.
    fn process<EHF: EnvoyHttpFilter>(&self, envoy: &mut EHF, body: Vec<u8>) {
        let req = build_request(&self.headers, body.clone());
        let mut actions = SdkActions::new(body);
        let _decision = self.shared.module.on_request(&req, &mut actions);
        actions.apply(envoy);
    }
}

/// Assemble a [`FilterRequest`] from the captured headers and body. The pseudo
/// headers (`:method`/`:path`/`:authority`) come from the enumerated header map.
fn build_request(headers: &[(String, String)], body: Vec<u8>) -> FilterRequest {
    let get = |name: &str| {
        headers
            .iter()
            .find(|(k, _)| k.eq_ignore_ascii_case(name))
            .map(|(_, v)| v.clone())
    };
    FilterRequest {
        method: get(":method").unwrap_or_default(),
        path_and_query: get(":path").unwrap_or_default(),
        authority: get(":authority").unwrap_or_default(),
        version: HttpVersion::Http2,
        headers: headers.to_vec(),
        body,
        identity: MtlsIdentity::default(),
    }
}

/// An owned recorder of the brain's effects (so it stays `Send`, as
/// [`EnvoyActions`] requires); [`SdkActions::apply`] commits them to the Envoy
/// handle after the async pipeline completes.
#[derive(Default)]
struct SdkActions {
    original_body: Vec<u8>,
    method: Option<String>,
    path: Option<String>,
    cluster: Option<String>,
    host: Option<String>,
    body: Option<Vec<u8>>,
    set_headers: Vec<(String, String)>,
    remove_headers: Vec<String>,
    immediate: Option<(u16, Vec<u8>)>,
}

impl SdkActions {
    fn new(original_body: Vec<u8>) -> Self {
        Self {
            original_body,
            ..Default::default()
        }
    }

    /// Commit: a fail-closed reply wins (stop the chain); otherwise apply the
    /// header/method/path rewrites and replace the body iff it changed.
    fn apply<EHF: EnvoyHttpFilter>(self, envoy: &mut EHF) {
        if let Some((status, body)) = self.immediate {
            envoy.send_response(u32::from(status), Vec::new(), Some(&body), None);
            return;
        }
        if let Some(method) = self.method {
            envoy.set_request_header(":method", method.as_bytes());
        }
        if let Some(path) = self.path {
            envoy.set_request_header(":path", path.as_bytes());
        }
        // The upstream host (from the placement endpoint): set it as the authority
        // so Envoy's dynamic-forward-proxy dials it. Harmless when the route targets
        // a normal cluster (the authority is not used for upstream selection there).
        if let Some(host) = self.host {
            envoy.set_request_header(":authority", host.as_bytes());
        }
        for (name, value) in self.set_headers {
            envoy.set_request_header(&name, value.as_bytes());
        }
        for name in self.remove_headers {
            envoy.remove_request_header(&name);
        }
        // Name the upstream cluster the placement chose, and drop the route Envoy
        // may have already computed so it re-matches on the header. A tenancy that
        // returns a different cluster per request then routes to a different
        // upstream — provided the bootstrap has header-matched routes for it (see
        // the multi-cluster example). `:path` is set to its final value above, so
        // the re-match never sees an empty path (the ext_proc 404 trap).
        if let Some(cluster) = self.cluster {
            envoy.set_request_header(evoxy_filter::CLUSTER_HEADER, cluster.as_bytes());
            envoy.clear_route_cache();
        }
        if let Some(body) = self.body {
            if body != self.original_body {
                // Replace the buffered body: drain the old bytes, append the new.
                let existing = envoy.get_buffered_request_body_size();
                if existing > 0 {
                    envoy.drain_buffered_request_body(existing);
                }
                envoy.append_buffered_request_body(&body);
                // Keep `content-length` in sync with the new body, or Envoy forwards
                // only the original length — truncating a grown body (e.g. `_tenant`
                // injection) and over-reading a shrunk one.
                envoy.set_request_header("content-length", body.len().to_string().as_bytes());
            }
        }
    }
}

impl EnvoyActions for SdkActions {
    // Record the placement's cluster; `apply` sets the routing header and clears the
    // route cache so Envoy re-matches on it (see `apply`). With a single-cluster
    // tenancy and a catch-all route this is a harmless no-op re-match; with
    // per-request clusters and header-matched routes it selects the upstream.
    fn set_upstream_cluster(&mut self, cluster: &str) {
        self.cluster = Some(cluster.to_owned());
    }
    fn set_upstream_host(&mut self, host: &str) {
        self.host = Some(host.to_owned());
    }
    fn set_method(&mut self, method: &str) {
        self.method = Some(method.to_owned());
    }
    fn set_path(&mut self, path: &str) {
        self.path = Some(path.to_owned());
    }
    fn set_body(&mut self, body: &[u8]) {
        self.body = Some(body.to_vec());
    }
    fn set_header(&mut self, name: &str, value: &str) {
        self.set_headers.push((name.to_owned(), value.to_owned()));
    }
    fn remove_header(&mut self, name: &str) {
        self.remove_headers.push(name.to_owned());
    }
    fn send_local_reply(&mut self, status: u16, _headers: &[(String, String)], body: &[u8]) {
        self.immediate = Some((status, body.to_vec()));
    }
}
